FROM ubuntu:latest AS base

RUN apt-get update

RUN apt install curl -y

RUN curl -sL https://deb.nodesource.com/setup_8.x 

RUN apt-get install nodejs npm -y

# RUN mkdir app

WORKDIR /app

COPY /react/ /app/

# RUN npm install

EXPOSE 3000

# CMD sh -c "npm install && npm start"