FROM debian:jessie-slim AS base

RUN apt-get update

RUN apt-get install python3-dev -y

RUN apt-get install python3-pip -y

RUN pip3 install gunicorn Flask flask-socketio flask-cors 

# RUN mkdir app

WORKDIR /app

COPY /backend /app

EXPOSE 5000

CMD gunicorn --bind 0.0.0.0:5000 wsgi:app


